Sync to mainstream commit d23570098cd161fe4d2fbedcd25f563a4ca1dbd8 (Thu, 29 Jul 2021 20:52:59 +0800)
Merge umkoin/umkoin#21882: build: Fix undefined reference to __mulodi4

Signed-off-by: Igor Gunia <vmta@yahoo.com>